blog/urls.py
from django.conf.urls import url
from blog import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^post/new/', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/$', views.DetailPostView.as_view(), name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.EditPostView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.DeletePostView.as_view(), name='post_delete'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.publish_post, name='post_publish'),
    url(r'^drafts/$', views.DraftsListView.as_view(), name='drafts'),
    url(r'^works/$', views.AllWorksListView.as_view(), name='works'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from users import views as userviews

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'login/$', userviews.UserLoginView.as_view(), name='login'),
    url(r'logout/$', userviews.UserLogoutView.as_view(), name='logout'),
    url(r'signup/$', userviews.SignupView.as_view(), name='signup'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from users.models import CustomUser
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    published = models.BooleanField(default=False)

    def publish(self):
        if self.published:
            self.published_date = None
            self.published = False
        else:
            self.published_date = timezone.now()
            self.published = True
        self.save()

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'pk': self.pk})

users/models.py
from django.contrib.auth.models import AbstractUser


# Create your models here.
class CustomUser(AbstractUser):
    def __str__(self):
        return self.username

blog/forms.py
from django import forms
from blog.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author', 'title', 'text')

users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')

blog/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from blog.models import Post
from blog.forms import PostForm


class PostListView(ListView):
    template_name = 'blog/post_list.html'
    context_object_name = 'posts_list'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published=True)


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post_create.html'
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm


class DetailPostView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'


class EditPostView(LoginRequiredMixin, UpdateView):
    model = Post
    login_url = '/login/'
    form_class = PostForm
    template_name = 'blog/post_create.html'


class DeletePostView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')
    template_name = 'blog/post_delete.html'
    context_object_name = 'object'


class DraftsListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'list'
    template_name = 'blog/drafts_list.html'
    user = None

    def get_queryset(self):
        return Post.objects.filter(author=self.user.pk).filter(published=False)

    def dispatch(self, request, *args, **kwargs):
        self.user = request.user
        return super(DraftsListView, self).dispatch(request, *args, **kwargs)


class AllWorksListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'list'
    template_name = 'blog/drafts_list.html'
    user = None

    def get_queryset(self):
        return Post.objects.filter(author=self.user.pk)

    def dispatch(self, request, *args, **kwargs):
        self.user = request.user
        return super(AllWorksListView, self).dispatch(request, *args, **kwargs)


@login_required
def publish_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_list')

users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from users.forms import CustomUserCreationForm


# Create your views here.
class UserLoginView(LoginView):
    template_name = 'login.html'
    success_url = reverse_lazy('blog:post_list')

    def get_success_url(self):
        return self.success_url


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('blog:post_list')


class SignupView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blog/templates/blog/drafts_list.html
{% extends 'blog/post_list.html' %}

{% block post_content %}
    {% if list %}
        {% for post in list %}
            <div class="card mb-3">
                <div class="card-header text-secondary">
                    <span class="badge badge-primary">Author: {{ post.author }}</span>
                    <span class="badge badge-info">Created Date: {{ post.created_date|date:"M Y" }}</span>
                    <span class="badge badge-success">
                    {% if post.published %}
                        Published
                    {% else %}
                        UnPublished
                    {% endif %}
                </span>
                </div>
                <div class="card-body">
                    <div class="card-title"><p class="h2">{{ post.title }}</p></div>
                    <div class="card-text">
                        {{ post.text }}
                        <p>Never in all their history have men been able truly to conceive of the world as
                            one: a single
                            sphere, a
                            occupy
                            as equals. The airman's earth, if free men make it, will be truly round: a globe
                            in practice,
                            not in
                            theory.</p>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row justify-content-around">
                        <a href="{% url 'blog:post_publish' pk=post.pk %}"
                           class="btn btn-outline-success col-2">Publish</a>
                        <a href="{% url 'blog:post_detail' pk=post.pk %}"
                           class="btn btn-outline-primary col-2">Detail</a>
                        <a href="{% url 'blog:post_edit' pk=post.pk %}"
                           class="btn btn-outline-warning col-2">Update</a>
                        <a href="{% url 'blog:post_delete' pk=post.pk %}"
                           class="btn btn-outline-danger col-2">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="card mb-3 message-box">
            <div class="card-body">
                <div class="card-text text-center">
                    It seems that you've got nothing! whoop!
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:post_list'%}"
                   class="btn btn-outline-success btn-block">Home</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/post_create.html
{% extends 'nav.html' %}
{% block custom_css %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}" type="text/css">
{% endblock %}

{% block content %}
    <section>
        <div class="post_create">
            <h2 class="text-center text-light" style="margin-top: 3rem;">New Post</h2>
            <form class="post-form col-12 col-sm-10" method="post" style="margin-top: 2rem;">
                {% csrf_token %}
                {#                wjcnote 这个地方传入的是 user.pk#}
                <input type="hidden" value="{{ user.pk }}" name="author" id="id_author">
                <div class="card-block">
                    <div class="card shadow">
                        <div class="card-header">
                            <label for="id_title" class="h5 m-0">Title:</label>
                        </div>
                        <div class="card-body" style="">
                            <input placeholder="Title" class="form-control" type="text" name="title" maxlength="200"
                                   required="" id="id_title" value="{{ post.title }}">
                        </div>
                    </div>
                </div>
                <div class="card-block mt-4">
                    <div class="card shadow">
                        <div class="card-header">
                            <label for="id_text" class="h5 m-0">Content:</label>
                        </div>
                        <div class="card-body mt-1">
                            <textarea class="form-control" name="text" rows="24" required="" id="id_text">{{ post.text|safe }}</textarea>
                        </div>
                    </div>
                </div>
                <button href="" type="submit" class="save btn btn-primary btn-block mt-4" style="margin:auto;">
                    Save
                </button>

            </form>
        </div>
    </section>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'nav.html' %}
{% block custom_css %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}" type="text/css">
{% endblock %}
{% block content %}
    <div class="delete-panel">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <br><strong class="text-danger">{{ object.title }}</strong>?
            </div>
            <input type="submit" class="btn btn-danger btn-block" name="" value="Confirm">
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/post_list.html' %}
{% block post_content %}
    <div class="card">
        <div class="card-header text-secondary">
            <span class="badge badge-primary">Author: {{ post.author }}</span>
            <span class="badge badge-info">Created Date: {{ post.created_date|date:"M Y" }}</span>
            <span class="badge badge-success">
                    {% if post.published %}
                        Published
                    {% else %}
                        UnPublished
                    {% endif %}
            </span>
        </div>
        <div class="card-body">
            <div class="card-title"><p class="h2">{{ post.title }}</p></div>
            <div class="card-text">
                {{ post.text }}
                <p>Never in all their history have men been able truly to conceive of the world as one: a single
                    sphere, a
                    globe, having the qualities of a globe, a round earth in which all the directions eventually
                    meet, in
                    which there is no center because every point, or none, is center — an equal earth which all men
                    occupy
                    as equals. The airman's earth, if free men make it, will be truly round: a globe in practice,
                    not in
                    theory.</p>
            </div>
        </div>

        <div class="card-footer">
            <div class="row justify-content-around">
                {% if post.author.pk == user.pk %}
                    <a href="{% url 'blog:post_edit' pk=post.pk %}" class="btn btn-warning col-3">Update</a>
                    <a href="{% url 'blog:post_delete' pk=post.pk %}" class="btn btn-danger col-3">Delete</a>
                {% endif %}
                <a href="{% url 'blog:post_list' %}" class="btn btn-secondary col-3">Home</a>
            </div>
        </div>

    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'nav.html' %}

{% block custom_css %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}" type="text/css">
{% endblock %}
{% block content %}
    <div class="left-panel pt-4">
        <div class="row post-content ml-3">
            {% block post_content %}
                {% if posts_list %}
                    {% for post in posts_list %}
                        <div class="card mb-3">
                            <div class="card-header text-secondary">
                                <span class="badge badge-primary">Author: {{ post.author }}</span>
                                <span class="badge badge-info">Created Date: {{ post.created_date|date:"M Y" }}</span>
                                <span class="badge badge-success">
                                    {% if post.published %}
                                        Published
                                    {% else %}
                                        UnPublished
                                    {% endif %}
                                </span>
                            </div>
                            <div class="card-body">
                                <div class="card-title"><p class="h2">{{ post.title }}</p></div>
                                <div class="card-text">
                                    {{ post.text }}
                                    <p>Never in all their history have men been able truly to conceive of the world as
                                        one: a single
                                        sphere, a
                                        occupy
                                        as equals. The airman's earth, if free men make it, will be truly round: a globe
                                        in practice,
                                        not in
                                        theory.</p>
                                </div>
                            </div>
                            {% if post.author.pk == user.pk %}
                                <div class="card-footer">
                                    <div class="row justify-content-around">
                                        <a href="{% url 'blog:post_publish' pk=post.pk %}"
                                           class="btn btn-outline-success col-2">
                                            {% if post.published %}
                                                unPublish
                                            {% else %}
                                                Publish
                                            {% endif %}
                                        </a>
                                        <a href="{% url 'blog:post_detail' pk=post.pk %}"
                                           class="btn btn-outline-primary col-2">Detail</a>
                                        <a href="{% url 'blog:post_edit' pk=post.pk %}"
                                           class="btn btn-outline-warning col-2">Update</a>
                                        <a href="{% url 'blog:post_delete' pk=post.pk %}"
                                           class="btn btn-outline-danger col-2">Delete</a>
                                    </div>
                                </div>
                            {% else %}
                                <div class="card-footer">
                                    <div class="row">
                                        <button class="btn btn-outline-primary btn-block">Detail</button>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endblock %}
        </div>
        <ul class="list-group text-center panel-content mr-3">
            {% if not user.is_authenticated %}
                <li class="list-group-item">
                    <a href="{% url 'login' %}" class="text-dark font-weight-bold">
                        <i class="fas fa-user fa-1x mr-2 text-success"></i>Log In</a></li>
                <li class="list-group-item">
                    <a href="{% url 'signup' %}" class="text-dark font-weight-bold">
                        <i class="fas fa-user-plus mr-2 text-success"></i>Sign Up</a></li>
            {% else %}
                <li class="list-group-item">
                    <a href="{% url 'logout' %}" class="text-dark font-weight-bold">
                        <i class="fas fa-sign-out-alt mr-2 text-success"></i>Log Out</a></li>
            {% endif %}
            <li class="list-group-item"><a href="{% url 'blog:post_new' %}" class="text-dark font-weight-bold">
                <i class="fas fa-plus mr-2 text-success"></i>Add Post</a></li>
            <li class="list-group-item"><a href="{% url 'blog:drafts' %}" class="text-dark  font-weight-bold">
                <i class="fas fa-drafting-compass mr-2 text-success"></i>All Drafts</a></li>
            <li class="list-group-item"><a href="{% url 'blog:works' %}" class="text-dark  font-weight-bold">
                <i class="fas fa-list mr-2 text-success"></i>All Works</a></li>
        </ul>
    </div>
{% endblock %}

templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts List</title>
    <!-- -->
    <!--wjcnote load bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--wjcnote load fonts and icons-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <!--wjcnote load static files-->
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/nav.css' %}" type="text/css">
    {% block custom_css %}

    {% endblock %}
</head>
<body>
<section>
    <div class="fixed-top">
        <nav class="navbar navbar-expand-md col-sm-12 bg-dark navbar-dark pl-4">
            <a href="#" class="navbar-brand"><i class="fas fa-blog text-success fa-2x"></i></a>
            <button type="button" class="navbar-toggler custom-toggler" data-toggle="collapse"
                    data-target="#nav-toggle-menu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="nav-toggle-menu">
                <ul class="navbar-nav">
                    <li class="nav-item"><a href="{% url 'blog:post_list' %}"
                                            class="nav-link text-uppercase text-light px-3 font-weight-bold">Public</a>
                    </li>
                    <li class="nav-item"><a href=""
                                            class="nav-link text-uppercase text-light px-3 font-weight-bold">Drafts</a>
                    </li>
                    <li class="nav-item"><a href=""
                                            class="nav-link text-uppercase text-light px-3 font-weight-bold">Github</a>
                    </li>

                </ul>
                <div class="row">
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="nav-link text-uppercase text-light px-1 font-weight-bold">
                            <i class="fas fa-user fa-1x pl-2 text-success"
                               style="padding-right: 0.4em"></i>{{ user.username }}</a>
                    {% endif %}
                    <form class="form-inline ml-3">
                        <div class="input-group">
                            <input type="text" placeholder="Search" class="form-control">
                            <div class="input-group-append">
                                <button type="button" class="btn btn-light mr-3"><i
                                        class="fas fa-search text-success"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </nav>
    </div>
</section>

<div class="bg-secondary" style="height: 96vh; margin-top: 60px">
    {% block content %}
    {% endblock %}
</div>


<!--wjcnote load script files-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

users/templates/login.html
{% extends 'nav.html' %}
{% block custom_css %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
{% endblock %}
{% block content %}
    <div class="bg-secondary login-background">

        <div class="form-login form-group mb-0 bg-light">
            <form method="POST">
                {% csrf_token %}
                <h1 class="logo  mt-4"><i class="fas fa-blog fa-2x text-success"></i></h1>
                <h1 class="h3 mb-3 font-weight-normal text-center mt-4">LogIn</h1>
                <input type="text" class="form-control my-4" name="username" id="id_username" placeholder="Username:">
                <input type="password" class="form-control my-4" name="password" id="id_password" placeholder="Password:">
                <button type="submit" class="btn btn-success btn-block my-4">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/signup.html
{% extends 'nav.html' %}
{% block custom_css %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
    <div class="form-login form-group text-center">
        <form method="POST">
            {% csrf_token %}
            <h1 class="h2 mb-3 font-weight-normal text-success my-3">SignUp</h1>
            <input type="text" class="form-control my-2" name="username" id="id_username" placeholder="Username:">
            <input type="text" class="form-control my-2" name="email" id="id_email" placeholder="Email:">
            <input type="password" class="form-control my-2" name="password1" id="id_password1" placeholder="Password:">
            <input type="password" class="form-control my-2" name="password2" id="id_password2"
                   placeholder="Password again:">
            <button type="submit" class="btn btn-success btn-block my-4">Sign Up</button>
            <div class="">
                <ul class="error_list list-group">
                    {% for field in form %}
                        <li class="list-group-item list-group-item-primary">
                            {{ field.errors.as_text }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </form>
    </div>
{% endblock %}